export const API_EDT_CALL_IS_LOADING = "API_EDT_CALL_IS_LOADING";
export const API_EDT_CALL_HAS_ERROR = "API_EDT_CALL_HAS_ERROR";
export const API_EDT_CALL_DATA_SUCCESS = "API_EDT_CALL_DATA_SUCCESS";
