export const MERCHANT_SEARCH_IS_LOADING = "MERCHANT_SEARCH_IS_LOADING";
export const MERCHANT_SEARCH_HAS_ERROR = "MERCHANT_SEARCH_HAS_ERROR";
export const MERCHANT_SEARCH_DATA_SUCCESS = "MERCHANT_SEARCH_DATA_SUCCESS";

export const MERCHANT_DETAILS_IS_LOADING = "MERCHANT_DETAILS_IS_LOADING";
export const MERCHANT_DETAILS_HAS_ERROR = "MERCHANT_DETAILS_HAS_ERROR";
export const MERCHANT_DETAILS_DATA_SUCCESS = "MERCHANT_DETAILS_DATA_SUCCESS";

export const MERCHANT_API_EDT_CALL_IS_LOADING = "MERCHANT_API_EDT_CALL_IS_LOADING";
export const MERCHANT_API_EDT_CALL_HAS_ERROR = "MERCHANT_API_EDT_CALL_HAS_ERROR";
export const MERCHANT_API_EDT_CALL_DATA_SUCCESS = "MERCHANT_API_EDT_CALL_DATA_SUCCESS";

export const MERCHANT_API_CALL_IS_LOADING = "MERCHANT_API_CALL_IS_LOADING";
export const MERCHANT_API_CALL_HAS_ERROR = "MERCHANT_API_CALL_HAS_ERROR";
export const MERCHANT_API_CALL_DATA_SUCCESS = "MERCHANT_API_CALL_DATA_SUCCESS";
