export const ORDERS_SEARCH_IS_LOADING = "ORDERS_SEARCH_IS_LOADING";
export const ORDERS_SEARCH_HAS_ERROR = "ORDERS_SEARCH_HAS_ERROR";
export const ORDERS_SEARCH_DATA_SUCCESS = "ORDERS_SEARCH_DATA_SUCCESS";

export const ORDER_DETAILS_IS_LOADING = "ORDER_DETAILS_IS_LOADING";
export const ORDER_DETAILS_HAS_ERROR = "ORDER_DETAILS_HAS_ERROR";
export const ORDER_DETAILS_DATA_SUCCESS = "ORDER_DETAILS_DATA_SUCCESS";